// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzfzjedmfqjwfyhzchyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6ZnpqZWRtZnFqd2Z5aHpjaHliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Njk1MzQsImV4cCI6MjA2NjQ0NTUzNH0.qiJVKZuTX38eQREdkMEMm6Q49MBA-BiF1eNclzYIytI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);